"""Configuration dataclass for sortable queue instances."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/config.ipynb.

# %% auto #0
__all__ = ['SortableQueueConfig', 'get_item_key']

# %% ../nbs/config.ipynb #ykh0ivhpa6r
from dataclasses import dataclass, field
from typing import Optional, Callable

# %% ../nbs/config.ipynb #iqn7565lu0s
@dataclass
class SortableQueueConfig:
    """Configuration for a sortable queue instance."""
    prefix: str  # HTML ID prefix (e.g., "sq", "sd", "tss")
    key_field: str = "id"  # Field name to extract item key (simple case)
    key_fn: Optional[Callable[[dict], str]] = None  # Custom key extraction (overrides key_field if set)
    item_class: str = "queue-item"  # CSS class for queue items (keyboard selector + styling target)
    handle_class: str = "drag-handle"  # CSS class for Sortable.js drag handle
    animation_ms: int = 150  # Sortable.js drag animation duration in milliseconds
    queue_title: str = "Selected"  # Header title text

# %% ../nbs/config.ipynb #5jrlwvnzdai
def get_item_key(
    config: SortableQueueConfig,  # Queue configuration
    item: dict,  # Queue item dict
) -> str:  # Unique key string for the item
    """Extract the unique key from a queue item using the config's key_fn or key_field."""
    if config.key_fn is not None:
        return config.key_fn(item)
    return str(item.get(config.key_field, ""))
