"""Tier 1 handler functions for queue reorder, remove, and clear operations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/handlers.ipynb.

# %% auto #0
__all__ = ['handle_reorder', 'handle_reorder_by_direction', 'handle_remove', 'handle_clear']

# %% ../nbs/handlers.ipynb #eej96hunama
from typing import Any, Callable, List, Optional

from .config import SortableQueueConfig, get_item_key
from .html_ids import SortableQueueHtmlIds
from .models import SortableQueueUrls, reorder_by_keys, reorder_by_direction
from .rendering import render_sortable_queue

# %% ../nbs/handlers.ipynb #s08is8jh2nk
def handle_reorder(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints
    items: List[dict],  # Current item list
    new_key_order: List[str],  # Keys in new order (from form_data.getlist("item"))
    render_content: Callable[[dict, int], Any],  # Custom content callback
    **render_kwargs,  # Additional kwargs passed to render_sortable_queue
) -> tuple:  # (reordered_items, rendered_panel)
    """Reorder items by key order and return the updated list and rendered panel."""
    key_fn = lambda item: get_item_key(config, item)
    reordered = reorder_by_keys(items, new_key_order, key_fn)
    panel = render_sortable_queue(config, ids, urls, reordered, render_content, **render_kwargs)
    return reordered, panel

# %% ../nbs/handlers.ipynb #ofh1keercb
def handle_reorder_by_direction(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints
    items: List[dict],  # Current item list
    item_key: str,  # Key of item to move
    direction: str,  # "up" or "down"
    render_content: Callable[[dict, int], Any],  # Custom content callback
    **render_kwargs,  # Additional kwargs passed to render_sortable_queue
) -> tuple:  # (reordered_items, rendered_panel)
    """Move an item up or down and return the updated list and rendered panel."""
    key_fn = lambda item: get_item_key(config, item)
    reordered = reorder_by_direction(items, item_key, direction, key_fn)
    panel = render_sortable_queue(config, ids, urls, reordered, render_content, **render_kwargs)
    return reordered, panel

# %% ../nbs/handlers.ipynb #ovq0ujxp2q
def handle_remove(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints
    items: List[dict],  # Current item list
    remove_key: str,  # Key of item to remove
    render_content: Callable[[dict, int], Any],  # Custom content callback
    **render_kwargs,  # Additional kwargs passed to render_sortable_queue
) -> tuple:  # (updated_items, rendered_panel)
    """Remove an item by key and return the updated list and rendered panel."""
    key_fn = lambda item: get_item_key(config, item)
    updated = [item for item in items if key_fn(item) != remove_key]
    panel = render_sortable_queue(config, ids, urls, updated, render_content, **render_kwargs)
    return updated, panel

# %% ../nbs/handlers.ipynb #8fq8n2rh706
def handle_clear(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints
    render_content: Callable[[dict, int], Any],  # Custom content callback
    **render_kwargs,  # Additional kwargs passed to render_sortable_queue
) -> tuple:  # (empty_list, rendered_panel)
    """Clear all items and return an empty list and rendered panel."""
    panel = render_sortable_queue(config, ids, urls, [], render_content, **render_kwargs)
    return [], panel
