"""HTML element ID generators for sortable queue components."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['SortableQueueHtmlIds']

# %% ../nbs/html_ids.ipynb #kd2b1f804ff
import re
from dataclasses import dataclass

# %% ../nbs/html_ids.ipynb #6cg5wpl3t2m
def _safe_id(
    value: str,  # Raw value to sanitize
) -> str:  # HTML-safe ID fragment
    """Replace non-alphanumeric characters with hyphens for use in HTML IDs."""
    return re.sub(r'[^a-zA-Z0-9]', '-', value).strip('-')

# %% ../nbs/html_ids.ipynb #mlvsfrd42p
@dataclass
class SortableQueueHtmlIds:
    """HTML element ID generators for a sortable queue instance."""
    prefix: str  # Instance prefix (e.g., "sq", "sd", "tss")

    @property
    def container(self) -> str:  # Outer container div ID
        """Queue panel container."""
        return f"{self.prefix}-queue-container"

    @property
    def list(self) -> str:  # Sortable <ul> ID
        """Sortable queue list element."""
        return f"{self.prefix}-queue-list"

    @property
    def empty(self) -> str:  # Empty state div ID
        """Empty state placeholder."""
        return f"{self.prefix}-queue-empty"

    @property
    def header(self) -> str:  # Header section ID
        """Queue header section."""
        return f"{self.prefix}-queue-header"

    @property
    def remove_btn(self) -> str:  # Hidden keyboard remove button ID
        """Hidden button for keyboard-triggered remove."""
        return f"{self.prefix}-queue-remove-btn"

    @property
    def reorder_up_btn(self) -> str:  # Hidden keyboard reorder-up button ID
        """Hidden button for keyboard-triggered reorder up."""
        return f"{self.prefix}-queue-reorder-up-btn"

    @property
    def reorder_down_btn(self) -> str:  # Hidden keyboard reorder-down button ID
        """Hidden button for keyboard-triggered reorder down."""
        return f"{self.prefix}-queue-reorder-down-btn"

    @property
    def system_id(self) -> str:  # Keyboard system ID for hierarchy wiring
        """Keyboard system identifier for coordinator registration."""
        return f"{self.prefix}-queue-kb"

    def item(
        self,
        key: str,  # Item's unique key
    ) -> str:  # HTML ID for the queue item <li>
        """Per-item HTML ID."""
        return f"{self.prefix}-queue-item-{_safe_id(key)}"

    def as_selector(
        self,
        html_id: str,  # An HTML ID string
    ) -> str:  # CSS selector string
        """Convert an HTML ID to a CSS selector."""
        return f"#{html_id}"
