"""Self-contained keyboard system for sortable queue navigation and actions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/keyboard.ipynb.

# %% auto #0
__all__ = ['create_queue_keyboard_system']

# %% ../nbs/keyboard.ipynb #f8lak6tv4j
from typing import Optional

from cjm_fasthtml_keyboard_navigation.core.focus_zone import FocusZone
from cjm_fasthtml_keyboard_navigation.core.navigation import LinearVertical
from cjm_fasthtml_keyboard_navigation.core.actions import KeyAction
from cjm_fasthtml_keyboard_navigation.core.manager import ZoneManager
from cjm_fasthtml_keyboard_navigation.components.system import render_keyboard_system, KeyboardSystem

from cjm_fasthtml_tailwind.utilities.effects import ring
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui

from .config import SortableQueueConfig
from .html_ids import SortableQueueHtmlIds
from .models import SortableQueueUrls

# Default focused-item styling (matches cjm-fasthtml-virtual-collection convention)
_DEFAULT_ITEM_FOCUS_CLASSES = (str(bg_dui.base_300),)

# %% ../nbs/keyboard.ipynb #v0x9pvgwlqj
def create_queue_keyboard_system(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints for HTMX actions
    zone_focus_classes: tuple = (str(ring(0))),  # CSS classes when queue zone is active
    item_focus_classes: Optional[tuple] = None,  # CSS classes on focused item (default: bg-base-300)
    data_attributes: tuple = (),  # Data attributes to extract (e.g., ("record-id", "provider-id"))
    on_focus_change: Optional[str] = None,  # JS callback on item focus change
    hidden_input_prefix: Optional[str] = None,  # Prefix for hidden state inputs
    system_id: Optional[str] = None,  # Keyboard system ID (auto-generated from ids.system_id if not set)
    show_hints: bool = False,  # Show keyboard hints UI
) -> KeyboardSystem:  # Complete rendered keyboard system
    """Create a self-contained keyboard system for the sortable queue.

    Returns a rendered KeyboardSystem with a single FocusZone (LinearVertical
    navigation) and built-in actions for Delete/Backspace remove and
    Shift+Arrow reorder. Works standalone or as a child in a hierarchy
    via `coord.setParent(system_id, parent_id)`.
    """
    # Build the queue focus zone
    zone_kwargs = dict(
        id=ids.container,
        item_selector=f"li.{config.item_class}",
        navigation=LinearVertical(),
        item_focus_classes=item_focus_classes if item_focus_classes is not None else _DEFAULT_ITEM_FOCUS_CLASSES,
    )
    if zone_focus_classes:
        zone_kwargs["zone_focus_classes"] = zone_focus_classes
    if data_attributes:
        zone_kwargs["data_attributes"] = data_attributes
    if on_focus_change:
        zone_kwargs["on_focus_change"] = on_focus_change
    if hidden_input_prefix:
        zone_kwargs["hidden_input_prefix"] = hidden_input_prefix
    
    queue_zone = FocusZone(**zone_kwargs)
    
    # Built-in queue actions
    queue_zone_ids = (ids.container,)
    actions = (
        # Remove focused item (Delete)
        KeyAction(
            key="Delete",
            htmx_trigger=ids.remove_btn,
            zone_ids=queue_zone_ids,
            description="Remove from queue",
            hint_group="Queue",
        ),
        # Remove focused item (Backspace) — hidden alias
        KeyAction(
            key="Backspace",
            htmx_trigger=ids.remove_btn,
            zone_ids=queue_zone_ids,
            description="Remove from queue",
            hint_group="Queue",
            show_in_hints=False,
        ),
        # Reorder up (Shift+ArrowUp)
        KeyAction(
            key="ArrowUp",
            modifiers=frozenset({"shift"}),
            htmx_trigger=ids.reorder_up_btn,
            zone_ids=queue_zone_ids,
            description="Move up in queue",
            hint_group="Queue",
        ),
        # Reorder down (Shift+ArrowDown)
        KeyAction(
            key="ArrowDown",
            modifiers=frozenset({"shift"}),
            htmx_trigger=ids.reorder_down_btn,
            zone_ids=queue_zone_ids,
            description="Move down in queue",
            hint_group="Queue",
        ),
    )
    
    # Assemble ZoneManager
    manager = ZoneManager(
        zones=(queue_zone,),
        actions=actions,
        system_id=system_id or ids.system_id,
        state_hidden_inputs=True,
    )
    
    # URL/target/swap/vals maps for the hidden action buttons
    container_selector = ids.as_selector(ids.container)
    url_map = {
        ids.remove_btn: urls.remove,
        ids.reorder_up_btn: urls.reorder,
        ids.reorder_down_btn: urls.reorder,
    }
    target_map = {
        ids.remove_btn: container_selector,
        ids.reorder_up_btn: container_selector,
        ids.reorder_down_btn: container_selector,
    }
    swap_map = {
        ids.remove_btn: "outerHTML",
        ids.reorder_up_btn: "outerHTML",
        ids.reorder_down_btn: "outerHTML",
    }
    # Direction values distinguish up/down reorder buttons hitting the same URL
    vals_map = {
        ids.reorder_up_btn: {"direction": "up"},
        ids.reorder_down_btn: {"direction": "down"},
    }
    
    return render_keyboard_system(
        manager=manager,
        url_map=url_map,
        target_map=target_map,
        swap_map=swap_map,
        vals_map=vals_map,
        show_hints=show_hints,
    )
