"""URL bundle and reorder utility functions for sortable queues."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['SortableQueueUrls', 'reorder_by_keys', 'reorder_by_direction']

# %% ../nbs/models.ipynb #5hm5ym29glp
from dataclasses import dataclass
from typing import List, Callable

# %% ../nbs/models.ipynb #4n6jxy6ukk2
@dataclass
class SortableQueueUrls:
    """URL endpoints for sortable queue HTMX operations."""
    reorder: str  # POST — Sortable.js drag-end reorder
    remove: str   # POST — Remove item from queue
    clear: str    # POST — Clear all items

# %% ../nbs/models.ipynb #76ayn320jve
def reorder_by_keys(
    items: List[dict],  # Current item list
    new_key_order: List[str],  # Keys in desired order (from Sortable.js form data)
    key_fn: Callable[[dict], str],  # Function to extract key from item
) -> List[dict]:  # Reordered item list
    """Reorder items to match the key order from Sortable.js form data."""
    if not new_key_order:
        return list(items)
    lookup = {key_fn(item): item for item in items}
    reordered = [lookup[k] for k in new_key_order if k in lookup]
    # Append any items not in the new order (safety fallback)
    new_order_set = set(new_key_order)
    for item in items:
        if key_fn(item) not in new_order_set:
            reordered.append(item)
    return reordered

# %% ../nbs/models.ipynb #jofbme60w6q
def reorder_by_direction(
    items: List[dict],  # Current item list
    item_key: str,  # Key of item to move
    direction: str,  # "up" or "down"
    key_fn: Callable[[dict], str],  # Function to extract key from item
) -> List[dict]:  # Reordered item list
    """Move an item up or down by swapping with its neighbor."""
    result = list(items)
    idx = next((i for i, item in enumerate(result) if key_fn(item) == item_key), None)
    if idx is None:
        return result
    if direction == "up" and idx > 0:
        result[idx], result[idx - 1] = result[idx - 1], result[idx]
    elif direction == "down" and idx < len(result) - 1:
        result[idx], result[idx + 1] = result[idx + 1], result[idx]
    return result
