"""Queue panel and item rendering with callback-based custom content."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/rendering.ipynb.

# %% auto #0
__all__ = ['render_queue_item', 'render_sortable_queue']

# %% ../nbs/rendering.ipynb #cpoa000mlcd
import json
from typing import Any, Callable, List, Optional

from fasthtml.common import Div, Span, Button, Ul, Li, P, Hidden

from cjm_fasthtml_daisyui.components.actions.button import btn, btn_sizes, btn_styles
from cjm_fasthtml_daisyui.components.data_display.badge import badge, badge_colors, badge_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, text_dui, border_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius

from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w
from cjm_fasthtml_tailwind.utilities.typography import (
    font_size, font_weight, text_align, list_style
)
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.utilities.interactivity import cursor
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, justify, items, grow
)
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_lucide_icons.factory import lucide_icon

from .config import SortableQueueConfig, get_item_key
from .html_ids import SortableQueueHtmlIds
from .models import SortableQueueUrls

# %% ../nbs/rendering.ipynb #wi0ki4vj48
def render_queue_item(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints
    item: dict,  # Queue item data
    index: int,  # 0-based position in queue
    render_content: Callable[[dict, int], Any],  # Callback for custom item content
    extra_attrs: Optional[dict] = None,  # Additional HTML attributes per item
) -> Any:  # Li element
    """Render a single queue item with drag handle, position, custom content, and remove button."""
    key = get_item_key(config, item)
    
    return Li(
        # Hidden input for Sortable.js form data collection
        Hidden(name="item", value=key),
        
        # Drag handle
        Span(
            lucide_icon("grip-vertical", size=4, cls=str(text_dui.base_content.opacity(40))),
            cls=combine_classes(config.handle_class, cursor.move, p.r(2))
        ),
        
        # Position number (1-based)
        Span(f"{index + 1}.", cls=combine_classes(font_weight.bold, p.r(2), w(6))),
        
        # Custom content from consumer callback
        render_content(item, index),
        
        # Remove button
        Button(
            lucide_icon("x", size=4, cls=str(text_dui.base_content.opacity(60))),
            cls=combine_classes(btn, btn_styles.ghost, btn_sizes.xs, m.l(1)),
            hx_post=urls.remove,
            hx_vals=json.dumps({"key": key}),
            hx_target=ids.as_selector(ids.container),
            hx_swap="outerHTML",
            data_action="remove",
            title="Remove from queue"
        ),
        
        id=ids.item(key),
        cls=combine_classes(
            config.item_class,
            flex_display,
            items.center,
            p(3),
            bg_dui.base_100,
            bg_dui.base_300.hover,
            overflow.x.auto
        ),
        data_key=key,
        **(extra_attrs or {})
    )

# %% ../nbs/rendering.ipynb #4jhpv848nwc
def _render_default_empty() -> Any:  # Empty state element
    """Default empty state when no items are in the queue."""
    return Div(
        P(
            "No items selected",
            cls=combine_classes(text_dui.base_content.opacity(40), text_align.center, font_size.sm)
        ),
        P(
            "Add items from the browser",
            cls=combine_classes(text_dui.base_content.opacity(30), text_align.center, font_size.xs)
        ),
        cls=combine_classes(p(8), flex_display, flex_direction.col, justify.center, items.center, grow())
    )

# %% ../nbs/rendering.ipynb #dp8t9qoxev6
def render_sortable_queue(
    config: SortableQueueConfig,  # Queue configuration
    ids: SortableQueueHtmlIds,  # HTML ID generators
    urls: SortableQueueUrls,  # URL endpoints
    queue_items: List[dict],  # Ordered list of queue item dicts
    render_content: Callable[[dict, int], Any],  # Callback for custom item content
    render_empty: Optional[Callable[[], Any]] = None,  # Custom empty state (default provided)
    render_header_actions: Optional[Callable[[List[dict], SortableQueueUrls], Any]] = None,  # Custom header actions
    render_footer: Optional[Callable[[List[dict]], Any]] = None,  # Optional footer content
    extra_item_attrs: Optional[Callable[[dict], dict]] = None,  # Additional data-* attributes per item
    container_classes: tuple = (),  # Additional classes on container div
) -> Any:  # Queue panel element
    """Render the complete sortable queue panel."""
    count = len(queue_items)
    has_items = count > 0
    
    # Header actions: default is a Clear button when items exist
    if render_header_actions is not None:
        header_actions = render_header_actions(queue_items, urls)
    elif has_items:
        header_actions = Button(
            "Clear",
            cls=combine_classes(btn, btn_styles.ghost, btn_sizes.xs),
            hx_post=urls.clear,
            hx_target=ids.as_selector(ids.container),
            hx_swap="outerHTML"
        )
    else:
        header_actions = None
    
    # Header
    header = Div(
        Div(
            Span(config.queue_title, cls=str(font_weight.bold)),
            Span(
                str(count),
                cls=combine_classes(badge, badge_colors.primary, badge_sizes.sm, m.l(2))
            ),
            cls=str(flex_display)
        ),
        header_actions,
        id=ids.header,
        cls=combine_classes(
            flex_display, justify.between, items.center,
            p(3), border_dui.base_200, border.b()
        )
    )
    
    # Body: queue list or empty state
    if has_items:
        li_items = [
            render_queue_item(
                config, ids, urls, item, i, render_content,
                extra_attrs=extra_item_attrs(item) if extra_item_attrs else None
            )
            for i, item in enumerate(queue_items)
        ]
        body = Ul(
            *li_items,
            id=ids.list,
            hx_post=urls.reorder,
            hx_trigger="end",
            hx_include="this",
            hx_target=ids.as_selector(ids.container),
            hx_swap="outerHTML",
            cls=combine_classes("sortable", grow(), overflow.y.auto, list_style.none, m(0), p(0))
        )
    else:
        empty_fn = render_empty or _render_default_empty
        body = Div(empty_fn(), id=ids.empty, cls=combine_classes(grow()))
    
    # Footer (optional)
    footer = render_footer(queue_items) if render_footer else None
    
    return Div(
        header,
        body,
        footer,
        id=ids.container,
        cls=combine_classes(
            bg_dui.base_200,
            border_radius.box,
            flex_display,
            flex_direction.col,
            overflow.hidden,
            *container_classes
        )
    )
