"""Tier 2 convenience router with auto-wired reorder, remove, and clear endpoints."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/router.ipynb.

# %% auto #0
__all__ = ['init_sortable_queue_router']

# %% ../nbs/router.ipynb #tlbk0bripsa
from typing import Any, Callable, List, Optional, Tuple

from fasthtml.common import APIRouter

from .config import SortableQueueConfig
from .html_ids import SortableQueueHtmlIds
from .models import SortableQueueUrls
from .handlers import handle_reorder, handle_remove, handle_clear

# %% ../nbs/router.ipynb #y6kzvuso5r
def init_sortable_queue_router(
    config: SortableQueueConfig,  # Queue configuration
    get_items: Callable[[str], List[dict]],  # (session_id) -> current items
    set_items: Callable[[str, List[dict]], None],  # (session_id, items) -> persist
    render_content: Callable[[dict, int], Any],  # Custom content callback
    on_mutate: Optional[Callable[[str, List[dict], str], tuple]] = None,  # (mutation_type, items, sess) -> OOB elements
    prefix: str = "/queue",  # Route prefix
    **render_kwargs,  # Additional kwargs passed to render_sortable_queue
) -> Tuple[APIRouter, SortableQueueUrls]:  # (router, urls) tuple
    """Initialize a router with reorder, remove, and clear endpoints.

    The `on_mutate` callback receives the mutation type ("reorder", "remove",
    "clear"), the updated items list, and the session ID. It should return a
    tuple of OOB elements to append to the response, or an empty tuple.
    """
    router = APIRouter(prefix=prefix)
    ids = SortableQueueHtmlIds(prefix=config.prefix)

    # Build URLs after router creation (prefix is applied)
    urls = SortableQueueUrls(
        reorder=f"{prefix}/reorder",
        remove=f"{prefix}/remove",
        clear=f"{prefix}/clear",
    )

    @router
    async def reorder(request, sess):
        """Handle Sortable.js drag-end reorder."""
        form_data = await request.form()
        new_key_order = form_data.getlist("item")
        items = get_items(sess)
        updated, panel = handle_reorder(config, ids, urls, items, new_key_order, render_content, **render_kwargs)
        set_items(sess, updated)
        if on_mutate:
            oob = on_mutate("reorder", updated, sess)
            if oob:
                return (panel, *oob)
        return panel

    @router
    async def remove(request, sess, key: str = ""):
        """Handle item removal."""
        items = get_items(sess)
        updated, panel = handle_remove(config, ids, urls, items, key, render_content, **render_kwargs)
        set_items(sess, updated)
        if on_mutate:
            oob = on_mutate("remove", updated, sess)
            if oob:
                return (panel, *oob)
        return panel

    @router
    async def clear(sess):
        """Handle clear all."""
        updated, panel = handle_clear(config, ids, urls, render_content, **render_kwargs)
        set_items(sess, updated)
        if on_mutate:
            oob = on_mutate("clear", updated, sess)
            if oob:
                return (panel, *oob)
        return panel

    return router, urls
