"""Sortable.js CDN loading and initialization script generation.

Docs: https://cj-mills.github.io/cjm-fasthtml-sortable-queuesortable_js.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/sortable_js.ipynb.

# %% auto #0
__all__ = ['SORTABLE_JS_CDN', 'sortable_js_headers', 'generate_sortable_init_script']

# %% ../nbs/sortable_js.ipynb #qge77gyg7w
from fasthtml.common import Script

# %% ../nbs/sortable_js.ipynb #0rdx39x7pf2
SORTABLE_JS_CDN = "https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"

# %% ../nbs/sortable_js.ipynb #838cosyhc8q
def sortable_js_headers() -> tuple:  # Tuple of Script elements for app headers
    """CDN script tag for Sortable.js, suitable for FastHTML app headers."""
    return (Script(src=SORTABLE_JS_CDN),)

# %% ../nbs/sortable_js.ipynb #agw1tbp9z1p
def generate_sortable_init_script(
    handle_class: str = "drag-handle",  # CSS class for drag handle elements
    animation_ms: int = 150,  # Drag animation duration in milliseconds
) -> Script:  # Script element with Sortable.js initialization
    """Generate htmx.onLoad script that initializes Sortable.js on `.sortable` elements.

    Includes the disable-on-drag/re-enable-on-swap pattern to prevent
    double-firing during HTMX response processing.
    """
    return Script(f"""
htmx.onLoad(function(content) {{
    var sortables = content.querySelectorAll(".sortable");
    for (var i = 0; i < sortables.length; i++) {{
        var sortable = sortables[i];
        var sortableInstance = new Sortable(sortable, {{
            animation: {animation_ms},
            handle: ".{handle_class}",
            onEnd: function(evt) {{
                this.option("disabled", true);
            }}
        }});
        sortable.addEventListener("htmx:afterSwap", function() {{
            sortableInstance.option("disabled", false);
        }});
    }}
}});
""")
